version: 0.0
os: linux
files:
  - source: build/libs/backend-0.0.1-SNAPSHOT.jar
    destination: /home/ubuntu/
    overwrite: yes

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu
