version: 0.0
os: linux

files:
  - source: newsummarize.jar
    destination: /home/ec2-user/newsummarize
  - source: scripts/deploy.sh
    destination: /home/ec2-user/newsummarize/scripts

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu

