version: 0.0
os: linux
files:
  - source: build/libs/newsummarize.jar
    destination: /home/ubuntu/
  - source: scripts/deploy.sh
    destination: /home/ubuntu/

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu
