version: 0.0
os: linux

files:
  - source: backend-0.0.1-SNAPSHOT.jar
    destination: /home/ubuntu
  - source: scripts/deploy.sh
    destination: /home/ubuntu/scripts

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu
