version: 0.0
os: linux

files:
  - source: build/libs/backend-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/newsummarize
    overwrite: yes
  - source: scripts/deploy.sh
    destination: /home/ec2-user/newsummarize/scripts
    overwrite: yes

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ec2-user
