version: 0.0
os: linux
files:
  - source: build/libs/
    destination: /home/ubuntu
  - source: scripts/
    destination: /home/ubuntu/scripts
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu
