version: 0.0
os: linux
files:
  - source: build/libs/newsummarize-0.0.1-SNAPSHOT.jar
    destination: /home/ubuntu/
  - source: scripts/deploy.sh
    destination: /home/ubuntu/

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: ubuntu
