version: 0.0
os: linux
files:
  - source: build/libs/backend-0.0.1-SNAPSHOT.jar
    destination: /home/ubuntu/

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu

permissions:
  - object: /home/ubuntu
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
