phases:
  build:
    commands:
      - echo "[BUILD] Building the Spring Boot JAR..."
      - ./gradlew clean build -x test
      - cp build/libs/backend-0.0.1-SNAPSHOT.jar newsummarize.jar  # 파일명 명확히 지정

artifacts:
  files:
    - newsummarize.jar
    - appspec.yml
    - scripts/deploy.sh
  discard-paths: yes
