version: 0.2

phases:
  build:
    commands:
      - echo "[BUILD] Building the Spring Boot JAR..."
      - ./gradlew clean build -x test
      - |
        JAR_FILE=$(find build/libs -name "*.jar" ! -name "*plain*" | head -n 1)
        echo "Found JAR: $JAR_FILE"
        cp "$JAR_FILE" newsummarize.jar

artifacts:
  files:
    - newsummarize.jar
    - appspec.yml
    - scripts/deploy.sh
  discard-paths: yes

