version: 0.2

phases:
  build:
    commands:
      - echo "[BUILD] Cleaning and building..."
      - ./gradlew clean build -x test
      - cp build/libs/backend-0.0.1-SNAPSHOT.jar backend-0.0.1-SNAPSHOT.jar

artifacts:
  files:
    - backend-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - scripts/deploy.sh
  discard-paths: yes
