version: 0.2

phases:
  build:
    commands:
      - echo "[BUILD] Building the Spring Boot JAR..."
      - ./gradlew clean build -x test
      - cp build/libs/*.jar newsummarize.jar  # 여기에서 바로 복사

artifacts:
  files:
    - newsummarize.jar
    - appspec.yml
    - scripts/deploy.sh
  discard-paths: yes
