version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "📦 Installing dependencies..."
      - chmod +x gradlew
  build:
    commands:
      - echo "🚀 Building JAR..."
      - ./gradlew clean build -x test
      - echo "📁 Packaging deployment bundle..."
      - cp build/libs/backend-0.0.1-SNAPSHOT.jar .
      - cp appspec.yml .
      - mkdir -p scripts
      - cp scripts/deploy.sh scripts/deploy.sh
artifacts:
  files:
    - backend-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - scripts/**   # 배포 스크립트 포함
