version: 0.2

phases:
  build:
    commands:
      - echo "[BUILD] Building the Spring Boot JAR..."
      - ./gradlew clean build -x test

artifacts:
  files:
    - build/libs/backend-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - scripts/deploy.sh
  discard-paths: yes
