version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - chmod +x gradlew
  build:
    commands:
      - echo "Building project..."
      - ./gradlew clean build -x test

artifacts:
  base-directory: .
  files:
    - build/libs/backend-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - scripts/**
