version: 0.2

phases:
  install:
    commands:
      - echo "Installing..."
      - chmod +x gradlew
  build:
    commands:
      - echo "Building..."
      - ./gradlew clean build -x test

artifacts:
  files:
    - build/libs/*.jar
    - appspec.yml
    - scripts/deploy.sh
