version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - chmod +x gradlew
  build:
    commands:
      - echo "Building project..."
      - ./gradlew clean build -x test

artifacts:
  base-directory: build/libs
  files:
    - backend-0.0.1-SNAPSHOT.jar
  secondary-artifacts:
    deploy:
      base-directory: .
      files:
        - appspec.yml
        - scripts/deploy.sh
