version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - chmod +x gradlew
  build:
    commands:
      - echo "Building project..."
      - ./gradlew clean build -x test

artifacts:
  base-directory: . # ← 꼭 추가해줘!
  files:
    - build/libs/*.jar
    - appspec.yml
    - scripts/deploy.sh
