version: 0.2

phases:
  build:
    commands:
      - echo "[BUILD] Building the Spring Boot JAR..."
      - ./gradlew clean build -x test
      - ls build/libs  # ✅ JAR 파일이 생성됐는지 확인 로그 출력
      - cp build/libs/backend-0.0.1-SNAPSHOT.jar ./newsummarize.jar

artifacts:
  files:
    - newsummarize.jar
    - appspec.yml
    - scripts/deploy.sh
  discard-paths: yes
