version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "📦 Installing dependencies..."
      - chmod +x gradlew
  build:
    commands:
      - echo "🚀 Building JAR..."
      - ./gradlew clean build -x test
      - echo "📁 Packaging deployment bundle..."
      - mkdir -p deploy_bundle
      - cp build/libs/backend-0.0.1-SNAPSHOT.jar deploy_bundle/
      - cp appspec.yml deploy_bundle/
      - cp -r scripts deploy_bundle/
      - cd deploy_bundle
      - zip -r ../newsummarize-v1.zip .
      - cd ..
artifacts:
  files:
    - newsummarize-v1.zip
