phases:
  build:
    commands:
      - echo "[BUILD] Building the Spring Boot JAR..."
      - ./gradlew clean build -x test
      - cp build/libs/*.jar ./newsummarize.jar

artifacts:
  files:
    - newsummarize.jar
    - appspec.yml
    - scripts/deploy.sh
  discard-paths: yes
