version: 0.2

phases:
  build:
    commands:
      - echo "[BUILD] Cleaning and building..."
      - ./gradlew clean build -x test
      - |
        JAR_FILE=$(find build/libs -name "*.jar" ! -name "*plain*" | head -n 1)
        echo "[BUILD] Found jar: $JAR_FILE"
        cp "$JAR_FILE" backend-0.0.1-SNAPSHOT.jar


artifacts:
  files:
    - backend-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - scripts/deploy.sh
  discard-paths: yes
