# CodeBuild 사양 버전 (고정값: 0.2 사용)
version: 0.2

phases:
  install:
    commands:
      # 의존성 설치 등 초기 작업 (필요 시 추가 가능)
      - echo "[BUILD] Installing dependencies..."

  build:
    commands:
      # 빌드 작업 수행
      - echo "[BUILD] Building the Spring Boot JAR..."
      - ./gradlew clean build -x test  # 테스트는 제외하고 빌드 수행

artifacts:
  files:
    # S3 또는 CodeDeploy로 전달할 파일 목록 지정
    - build/libs/*.jar               # 빌드된 JAR 파일
    - appspec.yml                    # CodeDeploy 배포 스크립트 정의 파일
    - scripts/deploy.sh             # 배포 후 실행될 스크립트

  discard-paths: yes                # 디렉토리 구조 제거 후 파일만 루트에 업로드
