spring:
  datasource:
    url: jdbc:mysql://news-db.cjg2aaai646f.ap-northeast-2.rds.amazonaws.com:3306/newsdb
    username: songsungmin                      # RDS MySQL 사용자명
    password: password0419                     # RDS MySQL 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL 드라이버 클래스

  jpa:
    hibernate:
      ddl-auto: none                           # 테이블 자동 생성 안 함 (none, update, create 등 설정 가능)
    show-sql: true                             # 실행되는 SQL 로그 출력
    properties:
      hibernate:
        format_sql: true                       # SQL 쿼리를 보기 좋게 포맷팅

  data:
    redis:
      host: 127.0.0.1                           # Redis 서버 호스트 (EC2 내부에서 접근)
      port: 6379                                # Redis 기본 포트
      password: password0419                   # Redis 서버 비밀번호 (직접 설정한 값)
      timeout: 6000                            # 연결 타임아웃 (ms 단위)
      lettuce:
        pool:
          enabled: true                        # Lettuce 연결 풀 사용 활성화

  main:
    lazy-initialization: true                  # Bean 지연 초기화 (성능 향상에 도움)

logging:
  level:
    root: info                                  # 전체 로그 레벨 기본값 (info 이상 출력)

jwt:
  secret: "newsummarize-project-super-secret-key-2025!"  # JWT 서명용 비밀키
  expiration: 3600000                                      # JWT 토큰 만료 시간 (1시간 = 3600000ms)

jvm:
  memory:
    xmx: 2g                                     # JVM 최대 힙 메모리 크기 설정
    xms: 1g                                     # JVM 초기 힙 메모리 크기 설정

server:
  port: 8080                                    # 백엔드 서버 포트
  address: 0.0.0.0                              # 외부 IP로도 접근 가능하게 설정
