spring:
  datasource:
    url: jdbc:mysql://news-db.cjg2aaai646f.ap-northeast-2.rds.amazonaws.com:3306/newsdb
    username: songsungmin
    password: password0419
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: password0419  # EC2에 설정한 비번
      timeout: 6000
      lettuce:
        pool:
          enabled: true

  main:
    lazy-initialization: true

logging:
  level:
    root: info


jwt:
  secret: "newsummarize-project-super-secret-key-2025!"
  expiration: 3600000

jvm:
  memory:
    xmx: 2g
    xms: 1g